apiVersion: v1
kind: Pod
metadata:
   name: mypod1
spec:
    containers:
       - image: mysql
         name: mycont
         ports: 
          - containerPort: 3306
         env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mazaconfig
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mazaconfig
                key: MYSQL_DATABASE
