apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:   # Corrected spelling
      labels:
        app: myapp
    spec:
      restartPolicy: OnFailure   # Fixed indentation
      containers:
        - name: jobcont
          image: luksa/batch-job

