apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
spec:
    replicas: 3
    selector:
      matchLabels:
        app: test
    template:
      metadata:
         labels:
          app: test
      spec:
        containers:
         - image: nginx
           name: mycont1
           ports:
             - containerPort: 80
           volumeMounts:
            - name: myvolume
              mountPath: /usr/share/nginx/html/

        volumes:
         - name: myvolume
           nfs:
             server: fs-0578fcd5c4e7e286b.efs.us-east-1.amazonaws.com
             path: /test
            
