apiVersion: v1
kind: PersistentVolume
metadata:
   name: mypv
   labels:
     app: dev
spec:
  capacity:
     storage: 20Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
   server: fs-02b4facb3fb8697ae.efs.us-east-1.amazonaws.com
   path: /pvcvolume
