apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mypvc
   labels:
     app: dev
spec:
  accessModes:
      - ReadWriteOnce
  resources:
   requests:
    storage: 10Gi
  selector:
    matchLabels:
      app: dev
