apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod
spec:
   replicas: 3
   template:
     metadata:
       labels:
         app: test
     spec: 
      containers:
        - image: nginx
          name: mycont
          ports:
           - containerPort: 80

